version: '3.8'
services:
    php:
        container_name: pragma-php
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - 8080:8080
        stdin_open: true
